# Generated by Django 5.2.11 on 2026-03-13 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fee', '0001_initial'),
        ('owner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodPermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_number', models.CharField(blank=True, max_length=150, null=True)),
                ('is_catering_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_late_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('catering_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('late_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('permit_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_permit_fee_paid', models.BooleanField(default=False)),
                ('application_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('est_name', models.CharField(blank=True, max_length=150, null=True)),
                ('est_phone', models.CharField(blank=True, max_length=150, null=True)),
                ('est_address', models.CharField(blank=True, max_length=200, null=True)),
                ('est_city', models.CharField(blank=True, max_length=150, null=True)),
                ('est_state', models.CharField(blank=True, max_length=150, null=True)),
                ('est_zip', models.CharField(blank=True, max_length=150, null=True)),
                ('manager_name', models.CharField(blank=True, max_length=150, null=True)),
                ('manager_phone', models.CharField(blank=True, max_length=150, null=True)),
                ('manager_email', models.CharField(blank=True, max_length=150, null=True)),
                ('is_copy_est', models.BooleanField(default=False)),
                ('is_copy_owner', models.BooleanField(default=False)),
                ('applicant_name', models.CharField(blank=True, max_length=150, null=True)),
                ('applicant_address', models.CharField(blank=True, max_length=200, null=True)),
                ('applicant_city', models.CharField(blank=True, max_length=150, null=True)),
                ('applicant_state', models.CharField(blank=True, max_length=150, null=True)),
                ('applicant_zip', models.CharField(blank=True, max_length=150, null=True)),
                ('risk', models.CharField(blank=True, max_length=125, null=True)),
                ('renewed', models.IntegerField(choices=[(0, 'Firstly Created'), (1, 'Renewed'), (2, 'Previous Row after Renewal')], default=0, help_text='0 => Firstly Created, 1 => Renewed, 2 => Previous Row after Renewal')),
                ('permit_status', models.CharField(blank=True, max_length=150, null=True)),
                ('active_date', models.DateField(blank=True, null=True)),
                ('previous_permit_status', models.CharField(blank=True, max_length=150, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_import', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_food_permits', to=settings.AUTH_USER_MODEL)),
                ('exp_permit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expired_permits', to='food_permits.foodpermit')),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fee.fee')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owners', to='owner.owner')),
                ('previous_permit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewed_permits', to='food_permits.foodpermit')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_food_permits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
