# Generated by Django 5.2.11 on 2026-03-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterPermitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('prefix', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=1)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
