# Generated by Django 5.2.11 on 2026-03-12 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_permit_type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classifications', models.CharField(blank=True, max_length=200, null=True)),
                ('base_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('month', models.CharField(blank=True, max_length=125, null=True)),
                ('employee', models.CharField(blank=True, max_length=125, null=True)),
                ('is_active', models.BooleanField(default=1)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('master_permit_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_permit_type.masterpermittype')),
            ],
        ),
    ]
